# Generated by Django 5.2.17 on 2026-09-21 20:25

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('category', models.CharField(choices=[('medical', 'Medical Records'), ('education', 'Education & Degrees'), ('vehicle', 'Vehicle & Asset'), ('personal', 'Personal & Identity'), ('professional', 'Professional & Employment'), ('other', 'Other Records')], default='other', max_length=50, verbose_name='Category Domain')),
                ('description', models.TextField(blank=True, verbose_name='Description / Notes')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, verbose_name='Vault File')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Original Filename')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='MIME / Content Type')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='File Size (Bytes)')),
                ('file_hash', models.CharField(blank=True, max_length=64, verbose_name='SHA-256 Checksum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Vault Owner')),
            ],
            options={
                'verbose_name': 'Vault Document',
                'verbose_name_plural': 'Vault Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='documents_d_user_id_c53b6e_idx'), models.Index(fields=['user', 'created_at'], name='documents_d_user_id_ffacf2_idx')],
            },
        ),
    ]
