# Generated by Django 5.2.17 on 2026-09-29 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('key_success', 'Key Verified'), ('key_failed', 'Invalid Key Attempt'), ('rate_locked', 'Brute-Force Lockout'), ('view_portal', 'Portal Session Opened'), ('view_doc', 'Document Previewed'), ('download_doc', 'Document Downloaded'), ('session_left', 'Session Closed'), ('pass_revoked', 'Pass Revoked by Owner'), ('pass_expired', 'Expired Access Attempt')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('locked', 'Locked'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='success', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('details', models.CharField(blank=True, default='', max_length=255)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='documents.document')),
                ('share_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='sharing.sharepass')),
            ],
            options={
                'verbose_name': 'Share Access Log',
                'verbose_name_plural': 'Share Access Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['share_pass', '-timestamp'], name='audit_share_share_p_28040d_idx'), models.Index(fields=['event_type', '-timestamp'], name='audit_share_event_t_f85765_idx')],
            },
        ),
    ]
