# Generated by Django 5.2.17 on 2026-09-22 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePass',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Optional description or purpose of this Share Pass', max_length=120)),
                ('key_hash', models.CharField(help_text='PBKDF2 cryptographic hash of the raw 8-character Share Key', max_length=255)),
                ('can_view', models.BooleanField(default=True, help_text='Permits in-browser decrypted viewing of shared documents')),
                ('can_download', models.BooleanField(default=False, help_text='Permits downloading raw decrypted files to recipient machine')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Strict expiration timestamp after which access is denied')),
                ('is_revoked', models.BooleanField(db_index=True, default=False, help_text='Immediate owner revocation flag')),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of successful accesses by recipients')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Maximum allowed accesses before pass expires (0 = unlimited during TTL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(related_name='share_passes', to='documents.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Share Pass',
                'verbose_name_plural': 'Share Passes',
                'ordering': ['-created_at'],
            },
        ),
    ]
